adds patient mapping
NHSDigital/direct-care-api pull request #116
Opened 2023-05-17 13:03 UTC by natasafrgk

2023-05-17 14:16 UTC, natasafrgk commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +
```
lambdas/orchestration/app/data_mapping/patient_mapping.py:72: in group_patient
    organisation_id = re.search(UUID_REGEX, organisation_ref).group().strip()  # type: ignore
E   AttributeError: 'NoneType' object has no attribute 'group'
```

I tried to add:
```
If not organisation_id: 
   pass
```
since the regex will never pick up the example_record.json IDs but nothing changed

2023-05-18 08:33 UTC, ed-bright requested changes
This is really good. A few small tweaks but otherwise it's ready to go - nice one!

2023-05-18 08:33 UTC, ed-bright commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +UUID_REGEX = r"[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}"
This is a duplicate - extract to retrieve_direct_mapping.py and rename that file to something like mapping utils

2023-05-18 08:33 UTC, ed-bright commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +    grouped_patient.update({"Patient": patient})
grouped_patient = {"Patient": patient}

2023-05-18 08:33 UTC, ed-bright commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +
matched_id = re.search(UUID_REGEX, organisation_ref)
if not matched_id:
    return {}
organisation_id = matched_id.group().strip()

2023-05-18 08:33 UTC, ed-bright commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +    if organisation_id == org_id:
Can you make these variable names clearer so it's easy to tell what's being compared?

2023-05-18 10:07 UTC, natasafrgk commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +    return ", ".join(filter(None, address))
We tested for an empty array, but the simple mapping returns an empty string for each empty field, so it becomes an array of empty strings which was still yielding 
```
", , , , "
```

I added a filter to exclude the empty string and return only "" if that's the case.

2023-05-18 11:02 UTC, natasafrgk commented
The regression testing is failing with :
```
Lambda execution failed with status 200 due to customer function error: Unable to import module 'app.orchestration_handler': No module named 'lambdas'.
```
Maybe the renaming of the mapping_utils file caused it some confusion, but it seems a bit of an extreme reason. I can not see any issue with the imports on the orchestration_handler locally.

2023-05-18 12:41 UTC, ed-bright commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +from lambdas.orchestration.app.lib.logger import write_log
This is the issue - should be a relative import

2023-05-18 12:41 UTC, ed-bright commented on lambdas/orchestration/app/data_mapping/patient_mapping.py
> +    return ", ".join(filter(None, address))
[x for x in address if x] is the more modern python way of filtering

2023-05-18 13:15 UTC, ed-bright approved these changes

2023-05-18 13:23 UTC, merged