Dicareapi 91/lambda data mapping
NHSDigital/direct-care-api pull request #123
Opened 2023-05-24 14:01 UTC by natasafrgk

2023-05-26 09:18 UTC, natasafrgk commented on terraform/api_gateway.tf
> +  authorization    = "NONE"
This annoys SonarCloud. Only picks up this line however and ignores the other path. 
The compliant solution I found was to change it to "AWS_IAM".

2023-05-26 15:46 UTC, ed-bright requested changes
Once you've fixed the uri on the api gateway try testing it on postman by grabbing the url and api key from the "build" Github action for the PR

2023-05-26 15:57 UTC, natasafrgk commented on terraform/api_gateway.tf
> +  uri                     = aws_lambda_function.lambda.invoke_arn
Ah, yes! I had a failing build due to changing names too deliberately, so I might have changed it back to `lambda` during the process. I'll amend it.

2023-05-26 15:58 UTC, natasafrgk commented on terraform/api_gateway.tf
> +  authorization    = "NONE"
I agree. Documentation allows for NONE, and IAM would add extra effort and complexity. I wanted to run it past you first.

2023-05-26 16:16 UTC, natasafrgk commented
> Once you've fixed the uri on the api gateway try testing it on postman by grabbing the url and api key from the "build" Github action for the PR

When no record was provided :
```
{
    "record": null,
    "message": "failed to get record",
    [...]
}
```

2023-05-30 09:56 UTC, ed-bright requested changes

2023-05-30 09:56 UTC, ed-bright commented on terraform/api_gateway.tf
> +  path_part   = "record"
maybe rename this to "map_gpcr"

2023-05-30 10:27 UTC, ed-bright approved these changes

2023-05-30 10:53 UTC, merged